Remove registry storage testdriver
distribution/distribution pull request #2766
Opened 2018-11-22 12:21 UTC by glefloch

This PR aims to close #2151 by removing the storage testdriver and using the inmemory driver. 
This also update the inmemory storage driver to make sure that any written data is not available before commit.

Signed-off-by: glefloch <glfloch@gmail.com>

2021-03-15 15:28 UTC, milosgajdos commented
@glefloch can you please rebase?

2022-04-02 20:07 UTC, milosgajdos commented
Ping @glefloch

2022-04-04 07:51 UTC, milosgajdos commented on registry/handlers/api_test.go
> +<<<<<<< HEAD
Hm, yeah, this won't work 😅

2022-04-04 08:01 UTC, milosgajdos commented
I think you might need to run `go mod tidy` and `go mod vendor` 🤔

2023-04-26 17:36 UTC, milosgajdos commented
@glefloch are you still interested in getting this PR done? There are some merge conflicts that need fixing

2023-04-26 18:12 UTC, glefloch commented
I need to set up my computer but yes, still interested into getting this merged!

2023-04-26 18:20 UTC, thaJeztah requested changes

2023-04-26 18:20 UTC, thaJeztah commented on registry/handlers/api_test.go
> +	_ "github.com/docker/distribution/registry/storage/driver/inmemory"
This should use the new location; using the old name causes the code from this repository (but the v2 release) to be vendored;


```go
	_ "github.com/distribution/distribution/v3/registry/storage/driver/inmemory"
```

2023-04-26 18:20 UTC, thaJeztah commented on registry/handlers/app_test.go
> +	"github.com/docker/distribution/registry/storage/driver/inmemory"
Same here;

```suggestion
	"github.com/distribution/distribution/v3/registry/storage/driver/inmemory"
```

2023-04-26 18:20 UTC, thaJeztah commented on registry/storage/blob_test.go
> +	"github.com/docker/distribution/registry/storage/driver/inmemory"
And here

2023-05-02 13:38 UTC, thaJeztah requested changes
Thanks!

Looks like there's still vendor changes related to your previous iteration; can you run;

```bash
go mod tidy
go mod vendor
```

And amend your commit with those changes?

2023-05-02 13:38 UTC, thaJeztah commented on go.sum
> +github.com/bmizerany/assert v0.0.0-20160611221934-b7ed37b82869/go.mod h1:Ekp36dRnpXw/yCqJaO+ZrUyxD+3VXMFFr56k5XYrpB4=
This is probably a left-over from your previous iteration (which was importing the old `github.com/docker/distribution`)

2023-05-02 13:38 UTC, thaJeztah commented on vendor/github.com/docker/distribution/LICENSE
> +Apache License
Same for all these files in `vendor`

2023-05-02 13:42 UTC, thaJeztah commented on registry/storage/blob_test.go
Looks like in this file you only updated the import, but forgot to replace references to the test-driver; for example, see line 26 (and some others);

https://github.com/distribution/distribution/blob/788598e23f50db1b2f89e780683a7a6a0eadf3d1/registry/storage/blob_test.go#L26-L26

2023-05-02 14:41 UTC, glefloch commented
It looks better thanks to `go mod` commands

2023-05-02 20:01 UTC, thaJeztah approved these changes
LGTM

ping @milosgajdos @corhere ptal

2023-05-02 20:03 UTC, corhere commented
@squizzi PTAL

2023-05-03 20:40 UTC, merged