Add new parameter s3accelerate to S3 storage driver.
distribution/distribution pull request #3181
Opened 2020-06-12 12:59 UTC by pimuzzo

Rebase of https://github.com/docker/distribution/pull/2166 due to inactivity

Original PR comment:
I've added an optional parameter to enable S3 Transfer acceleration for the S3 storage driver. Thank you very much for considering the change.

If s3accelerate is set to true then we turn on S3 Transfer Acceleration via the AWS SDK. It defaults to false since this is an opt-in feature on the S3 bucket.

Signed-off-by: Kirat Singh <kirat.singh@wsq.io>

2020-06-15 10:50 UTC, gionn commented
If anyone interested, we published a docker image with this patch applied on top of the 2.7 branch, and we are using it in production since friday to fix slow downloads speeds when S3 bucket is in a different region than clients pulling.

https://hub.docker.com/r/cloudesire/distribution/tags

2020-07-14 07:10 UTC, wy65701436 commented on registry/storage/driver/s3-aws/s3.go
> +	if params.S3Accelerate {
Minor comment: just use `awsConfig.WithS3UseAccelerate(params.S3Accelerate)`？It can be concise.

2020-07-14 07:28 UTC, wy65701436 commented
and it's better to revert the change of document as well. https://github.com/docker/docker.github.io/pull/10993/files

2020-09-08 15:14 UTC, thaJeztah commented
@pimuzzo looks like CI is failing because the second commit is missing a DCO sign-off in the commit message https://github.com/docker/distribution/blob/master/CONTRIBUTING.md#sign-your-work

2020-09-28 16:32 UTC, hectoragb commented
@thaJeztah Do we have an ETA for merging this PR?

2020-12-18 09:35 UTC, milosgajdos commented
@pimuzzo this patch looks great. Would you mind rebasing again, please?

2020-12-18 10:14 UTC, pimuzzo commented
@milosgajdos PR rebased

@wy65701436 @thaJeztah Fixed review and signed commits

2021-02-21 12:56 UTC, joaodrp commented on docs/configuration.md
> +    s3accelerate: false
```suggestion
   accelerate: false
```

I suggest removing the `s3` prefix. This config is under the S3 driver section, so the prefix is redundant.

2021-02-22 18:27 UTC, joaodrp approved these changes

2021-03-01 17:24 UTC, milosgajdos requested changes
@pimuzzo can you please update the S3 driver docs https://github.com/docker/docker.github.io/blob/master/registry/storage-drivers/s3.md as [the comment](https://github.com/distribution/distribution/pull/2166#issuecomment-274891232) on the original PR suggest?

2021-03-01 17:31 UTC, pimuzzo commented
@milosgajdos please take a look to https://github.com/docker/docker.github.io/pull/11140/files and leave me some comment on what you would change, it looks good to me

2021-06-01 13:40 UTC, gionn commented
@milosgajdos 🙏🏻

2022-04-01 21:55 UTC, milosgajdos commented
@pimuzzo can you rebase one more time. This LGTM and I'd like to give this 👍 so we can merge this in.

2022-04-04 16:39 UTC, milosgajdos commented
@pimuzzo can you sign your commits, please?

2022-04-04 17:25 UTC, pimuzzo commented
@milosgajdos I changed my workstation, please give me some time to fix all the things :D

2022-04-04 17:41 UTC, pimuzzo commented
@milosgajdos I did it :dancing_men:

2022-04-04 17:50 UTC, milosgajdos approved these changes

2022-04-04 17:50 UTC, merged