bugfix: if used cache, when delete a repository, should clear the cache, otherwise, can not push this repository again.
distribution/distribution pull request #3323
Opened 2021-01-05 14:58 UTC by dk-lockdown

ref: https://github.com/docker/distribution/issues/3322

2021-01-28 11:45 UTC, milosgajdos commented
@dk-lockdown thanks for the PR. Can you please add DCO signature as per [contribution guidelines](https://github.com/distribution/distribution/blob/main/CONTRIBUTING.md#sign-your-work)

2021-01-28 14:46 UTC, dk-lockdown commented
> @dk-lockdown thanks for the PR. Can you please add DCO signature as per [contribution guidelines](https://github.com/distribution/distribution/blob/main/CONTRIBUTING.md#sign-your-work)

signed

2021-03-23 09:50 UTC, dk-lockdown commented
@dmcgowan @stevvooe can you help me review this pr? thanks.

2021-03-26 09:03 UTC, dk-lockdown commented
@wy65701436 can you help me review this pr? thanks.

2021-08-16 07:58 UTC, CheneyCookie commented
Hi @dk-lockdown ,
I have tried with this commit changes, but the deleted repository still can't be pushed successful after GC, because of the blob cache.
This commit just clear the manifest cache after we sent a delete request, and then GC will remove the blobs without clear cache.
So that you can see you pushed the deleted repository successful after GC, but the registry will tell you "Layer already exists",
but it is just the cache, the registry didn't have these blobs.

Thanks.

2021-08-17 06:52 UTC, dk-lockdown commented
> Hi @dk-lockdown ,
> I have tried with this commit changes, but the deleted repository still can't be pushed successful after GC, because of the blob cache.
> This commit just clear the manifest cache after we sent a delete request, and then GC will remove the blobs without clear cache.
> So that you can see you pushed the deleted repository successful after GC, but the registry will tell you "Layer already exists",
> but it is just the cache, the registry didn't have these blobs.
> 
> Thanks.

this problem solved，clear the cache when gc.

2021-09-13 07:00 UTC, CheneyCookie commented
> > Hi @dk-lockdown ,
> > I have tried with this commit changes, but the deleted repository still can't be pushed successful after GC, because of the blob cache.
> > This commit just clear the manifest cache after we sent a delete request, and then GC will remove the blobs without clear cache.
> > So that you can see you pushed the deleted repository successful after GC, but the registry will tell you "Layer already exists",
> > but it is just the cache, the registry didn't have these blobs.
> > Thanks.
> 
> this problem solved，clear the cache when gc.

The trouble is distribution have two caches, one is global cache, one is repository scope cache.
In this clear cache commit https://github.com/distribution/distribution/pull/3323/commits/47f696d7f03aa1b0eec800f5ccd954be6f845664, it only clear the global cache, and the repository scope cache still exists.

2023-12-22 09:58 UTC, milosgajdos commented
Do you want to rebase @dk-lockdown

2023-12-25 03:09 UTC, dk-lockdown commented
> Do you want to rebase @dk-lockdown

rebased!

2024-01-23 03:11 UTC, dk-lockdown commented
@milosgajdos this pr need a review

2024-01-23 10:32 UTC, Jamstah requested changes
One thing missing from this PR is a test case.

Also, as the garbage collection runs in a separate process, I'm not sure this will actually clear an in-memory cache successfully. I expect it could clear a redis cache.

Overall, garbage collection is designed to be run while the registry is in readonly or stopped. To switch to read only (and back) means a restart of the registry process. This means for an in-memory cache, if the registry is being administered correctly, it would be cleared after GC anyway.

This PR should also update the documentation, perhaps both the garbage collection page and the caching configuration option, to explain what the registry administrator needs to know.

2024-01-23 10:32 UTC, Jamstah commented on registry/storage/linkedblobstore.go
> +	// See https://github.com/docker/distribution/issues/3322 to get more detail
The comment should explain the code. It can also link to a work item if you like, but the explanation should be in here.

2024-05-04 14:23 UTC, milosgajdos commented
Ping @dk-lockdown

2025-03-18 09:06 UTC, closed without merging