[release/2.7] update to go1.16
distribution/distribution pull request #3472
Opened 2021-07-30 23:49 UTC by thaJeztah

relates to https://github.com/distribution/distribution/pull/3466, as the updated github.com/golang-jwt/jwt v3.2.2 requires to 1.15 or 1.16

2021-07-31 10:46 UTC, milosgajdos approved these changes

2021-08-10 09:06 UTC, wy65701436 approved these changes
lgtm

2021-08-10 09:10 UTC, wy65701436 commented
we should also update https://github.com/distribution/distribution/blob/main/go.mod#L3

2021-08-10 09:13 UTC, wy65701436 requested changes
see the comments

2021-08-10 09:31 UTC, thaJeztah commented
> we should also update https://github.com/distribution/distribution/blob/main/go.mod#L3 and https://github.com/distribution/distribution/blob/main/Dockerfile#L1


This is the release/2.7 branch, so the `go.mod` doesn't apply. We also should not update the version in `go.mod` unless the code does not _work_ with older go versions (it specifies the minimum _required_ version to use, although currently only will print a warning).

> For the docker file, it probably needs to add ENV GO111MODULE auto

Ah, yes, that's a good catch; adding that.

2021-08-10 09:32 UTC, thaJeztah commented
Updated, PTAL

2021-08-10 09:47 UTC, thaJeztah commented
opened https://github.com/distribution/distribution/pull/3474 for the main branch

2021-08-10 10:32 UTC, wy65701436 approved these changes
lgtm

2021-08-10 10:34 UTC, wy65701436 commented
oh, yes, it's for v2.7

cc @milosgajdos  do we want to upgrade the golang major version in a patch release? I know it's caused by the jwt security issue.

2021-08-10 10:53 UTC, milosgajdos commented
> cc @milosgajdos do we want to upgrade the golang major version in a patch release? I know it's caused by the jwt security issue.

Not to sound SemVer pedantic, but we're talking about `minor` version upgrade here 

Even though `2.7` is quite behind the `main` and thus we might [reasonably] expect different performance, just for the sake of security we should go ahead with the upgrade 🤔

2021-08-10 10:59 UTC, merged

2021-08-10 11:04 UTC, thaJeztah commented
Yeah, older version of Go (<1.15) are no longer maintained, and may have unpatched security fixes that could affect this project. The Go language itself has a stability promise (`v1.xx` are promised to be backward compatible), but of course `stdlib` packages may have new additions (which in this case was needed for the jwt package)