Add baidu bos storage driver
distribution/distribution pull request #3490
Opened 2021-08-30 11:08 UTC by dolfly

Signed-off-by: Dolfly <dolfly@foxmail.com>

2023-03-18 05:44 UTC, garenwen approved these changes

2023-03-18 05:48 UTC, garenwen requested changes
lgtm

2023-03-18 18:22 UTC, milosgajdos commented
This PR needs a rebase but beware that we do not have any plans for adding support for additional storage drivers at the moment.

2023-08-20 13:36 UTC, milosgajdos commented
Closing. We are no longer accepting new storage drivers.

2023-08-20 13:36 UTC, closed without merging