Improve how reference regexps are built
distribution/distribution pull request #3566
Opened 2022-01-13 16:06 UTC by paulcacheux

This PR reduces the amount of `string -> *regexp.Regexp -> string` in reference Regexps. This conversion (especially the compilation is quite expensive both in memory and CPU usage.

This PR tries to be as minimal as possible by ensuring that the same regexps are exported (even those that are not really exported but just used in the same package) but I would be happy to change it to anything else if bigger changes are desired.

Signed-off-by: Paul Cacheux <paul.cacheux@datadoghq.com>

2022-01-13 18:11 UTC, deleteriousEffect commented
Looking at the code, it seems like it would be more efficient, but would you also mind providing a couple of benchmarks, so we can quantify the improvement?

2022-01-13 18:12 UTC, deleteriousEffect requested changes

2022-01-13 21:09 UTC, paulcacheux commented on reference/regexp.go
> +var re = regexp.MustCompile
Absolutely

2022-01-17 10:21 UTC, milosgajdos approved these changes
Nice! LGTM.

2022-01-18 18:24 UTC, deleteriousEffect commented
> Here is a repo with benchmarks around this PR https://github.com/paulcacheux/distrib-re-benchmark. Since it's benchmarking an init function it's a bit hacky but it works.

I really appreciate this, thank you!

For posterity, this is the output from my machine:

###### Previous
```
10:22 $ go test -bench=. -benchmem
goos: linux
goarch: amd64
pkg: example.com/previous
cpu: Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
BenchmarkPrevious-16                1269           1586451 ns/op         1339721 B/op      11453 allocs/op
PASS
ok      example.com/previous    2.114s
```

###### This PR
```
10:21 $ go test -bench=. -benchmem
goos: linux
goarch: amd64
pkg: example.com/pr
cpu: Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
BenchmarkPR-16              3660            822432 ns/op          485248 B/op       4501 allocs/op
PASS
ok      example.com/pr  3.047s
```

2022-01-18 18:26 UTC, deleteriousEffect commented
LGTM :rocket:

2022-01-18 18:26 UTC, merged