Add concurrency to tag Lookup
distribution/distribution pull request #3589
Opened 2022-02-17 10:00 UTC by bainsy88

This was to address performance issues when deleting images in repos with a large number of tagstore

https://github.com/distribution/distribution/issues/3525

Signed-off-by: jack-baines <jack.baines@uk.ibm.com>

2022-02-17 11:58 UTC, bainsy88 commented
This PR fixes 1 of the 2 things described in the issue which is that we have to look up every tag in the repo to detect whether it matches the digest being deleted and needs to be untagged and previously this was done one tag at a time. 

The 2nd bit has much lower impact from manual testing and is that once we have identified which tags match the digest we untag them sequentially.

2022-02-17 12:03 UTC, bainsy88 commented
Final thing to point out is that I have hardcoded the concurrency limit to 10 obviously may be some advantages to that being configurable but wasn't entirely sure on how that could be achieved, so if that is deemed required would appreciate a pointer of a similar code that gets config into something like the tag store.

2022-02-21 12:36 UTC, milosgajdos requested changes
Thanks, this looks good. I have a few nits if you don't mind :)

2022-02-21 12:36 UTC, milosgajdos commented on registry/storage/tagstore.go
> +
can we remove this empty line?

2022-02-21 12:36 UTC, milosgajdos commented on registry/storage/tagstore.go
> +			}
can we move this code into a `goroutine` (maybe allocate a chan and wait for it to finish?); it would be great to get rid of the break label 🤔

2022-02-21 12:41 UTC, milosgajdos commented
Just wondering since we are addressing these slow deletes...[this code](https://github.com/distribution/distribution/blob/a4d9db5a884b70be0c96dd6a7a9dbef4f2798c51/registry/storage/driver/s3-aws/s3.go#L873-L898) in S3 delete driver could use a bit of TLC, too. If the repo contains a lot of data, we end up growing `s3Objects` slice into huge size; the actual [deletes are batched](https://github.com/distribution/distribution/blob/main/registry/storage/driver/s3-aws/s3.go#L906-L917), though that is of little help since we must first go through all contents of the repo.

2022-03-21 13:32 UTC, wy65701436 commented on registry/storage/tagstore.go
> +	limiter := make(chan struct{}, 10)
and why chooses 10 or make it configurable just by env is enough?

2022-10-28 02:22 UTC, tiny1990 commented
LGTM...

800TB files in ceph ,its' hard to delete.
patch  it by this pr 

delete file with 3TB / min

2023-01-22 09:16 UTC, Antiarchitect commented
Is there any news on this?

2023-01-30 17:16 UTC, milosgajdos commented
Ping @bainsy88

2023-08-16 21:01 UTC, DavidSpek commented
Friendly ping @bainsy88

2023-08-16 21:33 UTC, milosgajdos commented
There is also https://github.com/distribution/distribution/pull/3890 which is more comprehensive.

We need to decide which one to keep focussing on.

2023-08-16 22:20 UTC, DavidSpek commented
If https://github.com/distribution/distribution/pull/3890 is more comprehensive and more (recently) active then I’d say it’s safe to close this PR (also given that the author hasn’t responded to the reviews).

2023-08-16 22:20 UTC, closed without merging