Fuzzing: Move over two fuzzers from cncf-fuzzing
distribution/distribution pull request #3795
Opened 2022-11-12 17:45 UTC by AdamKorcz

Move over [these two token fuzzers](https://github.com/cncf/cncf-fuzzing/blob/main/projects/distribution/token_fuzzer.go) from cncf-fuzzing. The dependencies come from `github.com/AdaLogics/go-fuzz-headers` which is used to create random structs.

Signed-off-by: AdamKorcz <adam@adalogics.com>

2022-12-06 23:41 UTC, corhere approved these changes

2022-12-06 23:52 UTC, thaJeztah requested changes
thanks! left two comments; can you look at those (and amend / squash the commit)?

2022-12-06 23:52 UTC, thaJeztah commented on go.mod
> +require github.com/AdaLogics/go-fuzz-headers v0.0.0-20221103172237-443f56ff4ba8
Can you move this one into the first (direct dependencies) block and rerun go mod tidy? Go doesn't always group them correct, and needs a bit of a nudge)

2022-12-06 23:52 UTC, thaJeztah commented on go.mod
> +require github.com/cyphar/filepath-securejoin v0.2.3 // indirect
same for this one, but this one is indirect so goes into the second block

2023-05-02 21:15 UTC, thaJeztah approved these changes
saw this one was still pending; I did a quick rebase, and fixed up the `go.mod` dependencies to be in the correct group

LGTM

2023-05-02 21:15 UTC, thaJeztah commented on vendor/github.com/kr/pretty/License
> -
See https://github.com/kr/pretty/pull/62

2023-05-02 21:16 UTC, thaJeztah commented
@milosgajdos @corhere as I was the last one pushing, perhaps one of you can (re-)LGTM and merge?

2023-05-02 21:23 UTC, corhere approved these changes

2023-05-03 13:13 UTC, milosgajdos commented
@AdamKorcz can you rebase and run `go mod tidy` - I see some stuff in `go.sum` that I think should get cleaned up by `tidy`

2023-05-03 14:35 UTC, thaJeztah commented
@milosgajdos I had the branch still checked out locally, but no diff on `go mod tidy`; anything specific that you were looking at?

2023-05-03 14:46 UTC, milosgajdos commented
@thaJeztah is it normal to see this -- there are two versions of `kr/text` in the `go.sum` 🤔 

```
github.com/kr/text v0.1.0/go.mod h1:4Jbv+DJW3UT/LiOwJeYQe1efqtUx/iVham/4vfdArNI=
github.com/kr/text v0.2.0 h1:5Nx0Ya0ZqY2ygV366QzturHI13Jq95ApcVaJBhpS+AY=
github.com/kr/text v0.2.0/go.mod h1:eLer722TekiGuMkidMxC/pM04lWEeraHUUmBw8l2grE=
```

2023-05-03 14:57 UTC, thaJeztah commented
Yeah, I think `go.sum` traverses all dependencies, then registers the checksum for each one it finds and uses to perform version resolution; https://go.dev/ref/mod#go-sum-files

> The go.sum file may contain hashes for multiple versions of a module. The go command may need to load go.mod files from multiple versions of a dependency in order to perform [minimal version selection](https://go.dev/ref/mod#minimal-version-selection). go.sum may also contain hashes for module versions that aren’t needed anymore (for example, after an upgrade). [go mod tidy](https://go.dev/ref/mod#go-mod-tidy) will add missing hashes and will remove unnecessary hashes from go.sum.

2023-05-03 14:59 UTC, milosgajdos commented
Sadness. That's not how I thought it was working. Thanks for the link and the quote.

2023-05-03 14:59 UTC, merged