garbage-collect --delete-untagged removes multi-arch manifests #3178
distribution/distribution pull request #3822
Opened 2023-01-09 07:55 UTC by readerx

resolve #3178

2023-01-11 03:46 UTC, readerx commented
@taharah 

please review the pr, tks~

2023-01-11 17:26 UTC, deleteriousEffect commented
@readerx thanks for the PR, please add a few tests in [`registry/storage/garbagecollect_test.go`](https://github.com/distribution/distribution/blob/main/registry/storage/garbagecollect_test.go).

These lists should cover:
 - a tagged manifestlist with untagged manifest references having the manifestlist and references still present after garbage collection
 - an untagged manifestlist with untagged references having the manifestlist and references removed after garbage collection
 - an untagged manifestlist with tagged references having the manifestlist removed, but the references still present after garbage collection
 - a tagged manifestlist with a deleted reference — garbage collection should continue without error here

2023-01-14 03:35 UTC, readerx commented
> @readerx thanks for the PR, please add a few tests in [`registry/storage/garbagecollect_test.go`](https://github.com/distribution/distribution/blob/main/registry/storage/garbagecollect_test.go).
> 
> These lists should cover:
> 
>     * a tagged manifestlist with untagged manifest references having the manifestlist and references still present after garbage collection
> 
>     * an untagged manifestlist with untagged references having the manifestlist and references removed after garbage collection
> 
>     * an untagged manifestlist with tagged references having the manifestlist removed, but the references still present after garbage collection
> 
>     * a tagged manifestlist with a deleted reference — garbage collection should continue without error here

thanks~

I added the test code and solved the test problem。

please review

2023-01-31 03:54 UTC, zkking commented
@thaJeztah I met same problem with @readerx ，Can you consider dealing with it as soon as possible？

2023-02-17 18:38 UTC, deleteriousEffect commented
@readerx sorry it took me so long to get back to you.

Thank you for writing the tests, I had some comments, but overall they accomplish what they need to very well :+1: 

I have some comments about the implementation, your solution works, and I'm grateful you've approached this nontrivial problem, but I think there are some issues which might become problems are registry and repository size increases.

2023-02-17 18:38 UTC, deleteriousEffect requested changes

2023-02-20 03:56 UTC, readerx commented on registry/storage/garbagecollect_test.go
> +	repo := makeRepository(t, registry, "sxxworfeai")
very good suggestions

2023-02-20 06:50 UTC, readerx commented on registry/storage/garbagecollect.go
> +		allTags, err := repository.Tags(ctx).All(ctx)
very well.

get all tags when needed

2023-02-20 06:51 UTC, readerx commented
> @readerx sorry it took me so long to get back to you.
> 
> Thank you for writing the tests, I had some comments, but overall they accomplish what they need to very well 👍
> 
> I have some comments about the implementation, your solution works, and I'm grateful you've approached this nontrivial problem, but I think there are some issues which might become problems are registry and repository size increases.

thanks~

I dealt with these problems，please review

2023-03-14 01:40 UTC, readerx commented
@deleteriousEffect  Is there anything else that needs to be modified?

2023-03-14 15:39 UTC, deleteriousEffect commented
@readerx sorry, we're waiting on another maintainer to review, we need to approvals.

2023-03-15 01:12 UTC, readerx commented
> @readerx sorry, we're waiting on another maintainer to review, we need two approvals.

Ok, I see. Thank you for your reply

2023-03-15 01:38 UTC, thaJeztah commented
Haven't done a review, but we probably want to clean up some of the commits before merging (at least I see there's some fix up commits in the PR)

2023-03-17 01:13 UTC, readerx commented
> Haven't done a review, but we probably want to clean up some of the commits before merging (at least I see there's some fix up commits in the PR)

Do I need to rebase some submit?

2023-04-12 06:05 UTC, readerx commented
> Haven't done a review, but we probably want to clean up some of the commits before merging (at least I see there's some fix up commits in the PR)

@thaJeztah 

I have merged the submission

2023-04-27 10:33 UTC, inakimalerba commented
I'm having the same issue on my local registry.

Just built and tested @readerx version and from an user point of view it works as expected.

Tested:
1. It doesn't purge multi-arch layers
2. It does correctly purge unreferenced layers when an image is updated


(1) was tested with the following snippet, which fails on master but is ok on this branch:

```bash
$ docker run --rm -it --net=host quay.io/skopeo/stable copy docker://debian:stable docker://localhost:5000/debian:stable --dest-tls-verify=false --multi-arch all
$ docker exec -it registry bin/registry garbage-collect --delete-untagged /registry.conf
$ docker pull localhost:5000/debian:stable
```

2023-06-16 09:16 UTC, inakimalerba commented
After running this patch for some time, we've run into the same problem in some occasions. The garbage collector fails trying to delete non existing files:

```
Jun 16 08:58:58 registry docker-compose[226492]: time="2023-06-16T08:58:58.197287132Z" level=info msg="deleting manifest: /docker/registry/v2/repositories/devops/container-images/mirrors/python/_manifests/revisions/sha256/65a02b97d160de7bc2d95d95a757454b86edf36d7506315b27d57ff2ecfc7217" go.version=go1.20.4 instance.id=2687ba10-6725-4dec-98fe-5092f044ff97 service=registry
Jun 16 08:58:58 registry docker-compose[226492]: time="2023-06-16T08:58:58.197743596Z" level=info msg="deleting manifest: /docker/registry/v2/repositories/devops/container-images/mirrors/python/_manifests/revisions/sha256/0545379b264455d536f53ebcda0a0eb2e864bf239bbd375b2b6543e6ef7c92cf" go.version=go1.20.4 instance.id=2687ba10-6725-4dec-98fe-5092f044ff97 service=registry
Jun 16 08:58:58 registry docker-compose[226492]: failed to garbage collect: failed to delete manifest sha256:0545379b264455d536f53ebcda0a0eb2e864bf239bbd375b2b6543e6ef7c92cf: filesystem: Path not found: /docker/registry/v2/repositories/devops/container-images/mirrors/python/_manifests/revisions/sha256/0545379b264455d536f53ebcda0a0eb2e864bf239bbd375b2b6543e6ef7c92cf
```

Any hint on where the problem could be would be appreciated. 

TIA

2023-06-16 09:36 UTC, readerx commented
> 

 Is there a way to reproduce it ?

2023-06-16 09:36 UTC, readerx commented
> After running this patch for some time, we've run into the same problem in some occasions. The garbage collector fails trying to delete non existing files:
> 
> ```
> Jun 16 08:58:58 registry docker-compose[226492]: time="2023-06-16T08:58:58.197287132Z" level=info msg="deleting manifest: /docker/registry/v2/repositories/devops/container-images/mirrors/python/_manifests/revisions/sha256/65a02b97d160de7bc2d95d95a757454b86edf36d7506315b27d57ff2ecfc7217" go.version=go1.20.4 instance.id=2687ba10-6725-4dec-98fe-5092f044ff97 service=registry
> Jun 16 08:58:58 registry docker-compose[226492]: time="2023-06-16T08:58:58.197743596Z" level=info msg="deleting manifest: /docker/registry/v2/repositories/devops/container-images/mirrors/python/_manifests/revisions/sha256/0545379b264455d536f53ebcda0a0eb2e864bf239bbd375b2b6543e6ef7c92cf" go.version=go1.20.4 instance.id=2687ba10-6725-4dec-98fe-5092f044ff97 service=registry
> Jun 16 08:58:58 registry docker-compose[226492]: failed to garbage collect: failed to delete manifest sha256:0545379b264455d536f53ebcda0a0eb2e864bf239bbd375b2b6543e6ef7c92cf: filesystem: Path not found: /docker/registry/v2/repositories/devops/container-images/mirrors/python/_manifests/revisions/sha256/0545379b264455d536f53ebcda0a0eb2e864bf239bbd375b2b6543e6ef7c92cf
> ```
> 
> Any hint on where the problem could be would be appreciated.
> 
> TIA

Is there a way to reproduce it ?

2023-06-16 10:03 UTC, inakimalerba commented
> > After running this patch for some time, we've run into the same problem in some occasions. The garbage collector fails trying to delete non existing files:
> > ```
> > Jun 16 08:58:58 registry docker-compose[226492]: time="2023-06-16T08:58:58.197287132Z" level=info msg="deleting manifest: /docker/registry/v2/repositories/devops/container-images/mirrors/python/_manifests/revisions/sha256/65a02b97d160de7bc2d95d95a757454b86edf36d7506315b27d57ff2ecfc7217" go.version=go1.20.4 instance.id=2687ba10-6725-4dec-98fe-5092f044ff97 service=registry
> > Jun 16 08:58:58 registry docker-compose[226492]: time="2023-06-16T08:58:58.197743596Z" level=info msg="deleting manifest: /docker/registry/v2/repositories/devops/container-images/mirrors/python/_manifests/revisions/sha256/0545379b264455d536f53ebcda0a0eb2e864bf239bbd375b2b6543e6ef7c92cf" go.version=go1.20.4 instance.id=2687ba10-6725-4dec-98fe-5092f044ff97 service=registry
> > Jun 16 08:58:58 registry docker-compose[226492]: failed to garbage collect: failed to delete manifest sha256:0545379b264455d536f53ebcda0a0eb2e864bf239bbd375b2b6543e6ef7c92cf: filesystem: Path not found: /docker/registry/v2/repositories/devops/container-images/mirrors/python/_manifests/revisions/sha256/0545379b264455d536f53ebcda0a0eb2e864bf239bbd375b2b6543e6ef7c92cf
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Any hint on where the problem could be would be appreciated.
> > TIA
> 
> Is there a way to reproduce it ?

Haven't found a way to reproduce it yet, but will keep trying and let you know.

One thing I know is that the error only happens on multi arch images, haven't seen it on the others.

2024-05-04 14:20 UTC, milosgajdos commented
Closing as resolved by https://github.com/distribution/distribution/pull/4285

2024-05-04 14:20 UTC, closed without merging