fix: ignore error of manifest tag path not found in gc
distribution/distribution pull request #4331
Opened 2024-04-19 04:08 UTC by microyahoo

it is reasonable to ignore the error that the manifest tag path does not exist when querying all tags of the specified repository when executing gc.

Signed-off-by: Liang Zheng <zhengliang0901@gmail.com>

2024-04-22 22:40 UTC, squizzi requested changes
I feel you could add a test for this that tests that GC does not error on an unknown repository, something like:

```go
func TestGCWithUnknownRepository(t *testing.T) {
	d := inmemory.New()

	registry := createRegistry(t, d)
	repo := makeRepository(t, registry, "nonexistentrepo")
	uploadRandomSchema2Image(t, repo)

	err := MarkAndSweep(dcontext.Background(), d, registry, GCOpts{
		DryRun:         false,
		RemoveUntagged: true,
	})
	if err != nil {
		t.Fatalf("got error: %v, expected nil", err)
	}
}
```

Passes with this addition but fails without it.

2024-04-22 22:40 UTC, squizzi commented on registry/storage/garbagecollect.go
> +						if errors.Is(err, distribution.ErrRepositoryUnknown{Name: repository.Named().Name()}) {
`repository.Named().Name()` isn't free, we're going to call it anyways to perform this err check so store it and then use it again in `emit` later, but what about the `repoName` string the `ingester` func uses above, is that not sufficient for this error check and the affiliated `emit`?

```suggestion
						if errors.Is(err, distribution.ErrRepositoryUnknown{Name: repoName}) {
```

2024-04-22 22:40 UTC, squizzi commented on registry/storage/garbagecollect.go
> +							emit("manifest tag path of repository %s not exist", repository.Named().Name())
```suggestion
							emit("manifest tag path of repository %s does not exist", repoName)
```

2024-04-23 03:03 UTC, microyahoo commented
hi @squizzi, seems PR https://github.com/distribution/distribution/pull/4285 has already coverred this scenario.

2024-04-23 17:36 UTC, squizzi commented
@microyahoo ya, it does.. I like your addition of having `emit` log when the repository is skipped.  Perhaps rebase and add that one line change?

2024-04-24 19:01 UTC, squizzi commented
@microyahoo good catch on the `ManifestUnknownRevision` error in the other PR, it seems yours is back on the table, let's get a test added for this, rebase and move forward with it.

2024-04-25 06:40 UTC, milosgajdos commented
@microyahoo there is a merge conflict now that needs fixing 😬

2024-04-25 07:50 UTC, microyahoo commented
> @microyahoo there is a merge conflict now that needs fixing 😬

hi @milosgajdos, thanks for you kindly reminder, I will fix it ASAP.

2024-04-25 16:57 UTC, milosgajdos approved these changes

2024-04-25 17:25 UTC, squizzi approved these changes

2024-04-25 17:25 UTC, merged